<PlayScreen>:

	BoxLayout:
		orientation: 'vertical'
		padding: (4,4)
		spacing: 4

		ScrollView:
			size_hint: (1,4)
			do_scroll_y: True

			Label:
				id: output
				text: ''
				size_hint_y: None
				text_size: self.width, None
				height: self.texture_size[1]

		BoxLayout:
			spacing: 4

			TextInput:
				id: input
				text: ''
				size_hint: (2,1)

			Button:
				id: send
				text: 'Send'
				on_release: root.on_send()
